image: maven:3.9-eclipse-temurin-17

stages:
  - build
  - test
  - package
  - docker-build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

docker-build:
  stage: docker-build
  image: docker:27
  services:
    - name: docker:27-dind
  dependencies:
    - package
  script:
    - docker info
    - docker build -t student-grade-app:1.0 .
    - docker images
